{
"version":3,
"file":"module$node_modules$core_js$library$modules$_iter_call.js",
"lineCount":1,
"mappings":"AAAAA,cAAA,CAAe,wDAAf,CAAA,CAA2E,QAAQ,CAACC,MAAD,CAAQC,OAAR,CAAgBC,OAAhB,CAAwBC,MAAxB,CAA+BC,OAA/B,CAAuCC,YAAvC,CAAqD,CAExI,IAAIC,SAAWJ,OAAA,CAAQ,wDAAR,CACfC,OAAAC,QAAA,CAAiBG,QAAS,CAACC,QAAD,CAAWC,EAAX,CAAeC,KAAf,CAAsBC,OAAtB,CAA+B,CACvD,GAAI,CACF,MAAOA,QAAA,CAAUF,EAAA,CAAGH,QAAA,CAASI,KAAT,CAAA,CAAgB,CAAhB,CAAH,CAAuBA,KAAA,CAAM,CAAN,CAAvB,CAAV,CAA6CD,EAAA,CAAGC,KAAH,CADlD,CAGF,MAAOE,CAAP,CAAU,CACV,IAAIC,IAAML,QAAA,CAAS,QAAT,CACV,IAAIK,GAAJ,GAAYC,SAAZ,CAAuBR,QAAA,CAASO,GAAAE,KAAA,CAASP,QAAT,CAAT,CACvB,MAAMI,EAAN,CAHU,CAJ2C,CAH+E;",
"sources":["node_modules/core-js/library/modules/_iter-call.js"],
"sourcesContent":["shadow$provide[\"module$node_modules$core_js$library$modules$_iter_call\"] = function(global,process,require,module,exports,shadow$shims) {\n// call something on iterator step with safe closing on error\nvar anObject = require('./_an-object');\nmodule.exports = function (iterator, fn, value, entries) {\n  try {\n    return entries ? fn(anObject(value)[0], value[1]) : fn(value);\n  // 7.4.6 IteratorClose(iterator, completion)\n  } catch (e) {\n    var ret = iterator['return'];\n    if (ret !== undefined) anObject(ret.call(iterator));\n    throw e;\n  }\n};\n\n};"],
"names":["shadow$provide","global","process","require","module","exports","shadow$shims","anObject","module.exports","iterator","fn","value","entries","e","ret","undefined","call"]
}
